import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  header: {
    height: 80,
    paddingTop: 30,
    backgroundColor: 'coral',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
  },
  title: {
    flex: 2,
    textAlign: 'center',
    color: 'black',
    fontSize: 22,
    fontWeight: 'bold',
  },
  container: {
    flex: 1,
    backgroundColor: 'azure',
    alignItems: 'center',
  },
  back: {
    backgroundColor: 'azure',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    borderWidth: 1,
    borderColor: '#777',
    padding: 8,
    margin: 15,
    width: 200,
  },
  inputReceipt: {
    borderWidth: 1,
    borderColor: '#777',
    padding: 2,
    margin: 15,
    width: 40,
  },
  buttonContainer: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    paddingHorizontal: 1,
    marginTop: 10,
    alignItems: 'center',
    width: '50%',
  },
  button: {
    width: '45%',
    marginHorizontal: 2,
  },

  square: {
    width: 300,
    height: 400,
    marginTop: 40,
    marginBottom: 50,
  },
  text: {
   textAlign: 'center', 
    color: 'black',
     fontWeight: 'bold', 
    fontSize: 18,
       },
  helloText : {
    textAlign: 'center', 
    color: 'black',
    fontWeight: 'bold', 
    fontSize: 24,
    marginTop:40,
    },

  slide: {
    marginTop: 50,
    width: '100%', 
    height: '7%', 
    backgroundColor: 'rgba(217, 58, 0, 1)', 
    justifyContent: 'center',
    flexDirection: 'row-reverse',
    paddingHorizontal: 10,
    alignItems: 'flex-start',
  },
  buttonSlied: {
    width: '100%', 
    marginTop: 10, 
    marginLeft: 30,
    paddingVertical: 10, 
    backgroundColor: 'rgba(217, 58, 0, 1)', 
    borderRadius: 18, 
    alignItems: 'center', 
    justifyContent: 'center', 
    fontWeight: 'bold', 
    textAlign: 'left',
    alignSelf: 'flex-start',
    fontSize: 15,
    flexDirection: 'row', 
    justifyContent: 'flex-end'

},
products: {
  width: '100%',
  paddingVertical: 2,
  borderRadius: 18,
  fontWeight: 'bold',
  fontSize: 15,
  borderWidth: 2,
  borderColor: 'black',
},
productsText:{
  fontWeight:'bold',
  fontSize: 17,
  textAlign: 'left',
  alignSelf: 'flex-end',
  alignItems: 'flex-start',
  justifyContent: 'flex-start',
},
productsButtons: {
  width: 40, 
  height: 40, 
  padding: 10, 
  borderRadius: 18,
  borderWidth: 2,
  marginTop:10,
  borderColor: 'black',
  alignSelf: 'flex-end',
},
inputDropdown: {
  borderWidth: 1,
  borderColor: '#777',
  padding: 1,
  margin: 10,
  width: 120,
},
lowerButtons: {
  height: 50,
  paddingTop: 0,
  backgroundColor: 'coral',
  justifyContent: 'space-between',
  alignItems: 'baseline',
  paddingHorizontal: 20,
},

buttonContainerReceipt: {
  flexDirection: 'row-reverse',
  justifyContent: 'flex-start',
  paddingHorizontal: 1,
  marginTop: -4,
  alignItems: 'center',
  width: '100%',
},
TotalPriceText:{
  fontWeight:'bold',
  fontSize: 22,
  textAlign: 'center',
  alignSelf: 'center',
  alignItems: 'center',
  justifyContent: 'center',
  top:5,
  left:10,
},
backArrow: {
  fontSize: 25,
  marginRight: 0,
  color: 'black',
},
model :{
  width: 300,
  height: 200,
  backgroundColor: 'white',
  marginTop: 350,
  marginLeft: 55,
  justifyContent: 'space-between',
  alignItems: 'center',
  flexDirection:'row' ,
  borderColor:'black',
  borderWidth: 3,
},

inputFade :{
position: 'absolute', 
top: 70 ,
left:40,
alignSelf: 'center' ,
},

buttonsFade :{
  flexDirection: 'row',
   justifyContent: 'space-around',
    width: '100%', 
    alignSelf: 'center',
    marginTop: 150 ,
    right:140,
},
percentageSign: {
  fontSize: 20,
  alignSelf: 'center',
  marginBottom:140,
  left:80,
},
buttonContainerCode: {
  marginTop: 20,
  alignItems: 'center',
  width: '40%',
},
preview: {
alignSelf: 'stretch',
flex: 1,
},
CameraButton: {
  flex: 1,
   justifyContent: 'flex-end', 
   marginBottom: 36,
},
innerCircle: {
  justifyContent: 'center',
  alignItems: 'center',
  width: 80,
  height: 80,
  borderRadius: 80, 
},
cameraButton: {
  borderRadius: 60, 
  backgroundColor: 'black', 
  padding: 10,
},
camera: {
  width: 100,
  height: 400,
  aspectRatio: 3/4,
  flex: 1,
},
menuIcon: {
  position: 'absolute',
  left: 20,
  top: 40,    
},
logoutButton: {
  position: 'absolute',
  right: 8, 
  top: 35, 
  padding: 10,
  borderRadius: 5,
},
logoutText: {
  color: 'white',
  fontWeight: 'bold',
},
leftContainer: {
  width: 100,
  flexDirection: 'column',
  alignItems: 'flex-end',
},
rightContainer: {
  width: 100,
  flexDirection: 'row',
  alignItems: 'flex-end',
},
modalOverlay: {
  flex: 1,
  backgroundColor: 'rgba(0,0,0,0.5)',
  justifyContent: 'flex-start',
},
sideMenu: {
  width: 250, 
  height: '100%',
  backgroundColor: 'coral',
  padding: 20,
  borderBottomRightRadius: 50,
  borderTopRightRadius: 50,
  position: 'absolute', 
  left: 0, 
  top: 0, 
  justifyContent: 'center', 
},
menuItem: {
  fontSize: 20, 
  paddingVertical: 15, 
  paddingHorizontal: 20, 
  borderRadius: 30, 
  textAlign: 'center', 
  marginBottom: 15, 
  elevation: 5, 
  shadowColor: '#000', 
  shadowOffset: { width: 0, height: 2 }, 
  shadowOpacity: 0.3,
  shadowRadius: 3, 
  color: 'black',
  fontWeight: 'bold', 
},
menuItemPressed: {
  backgroundColor: '#ffd700', 
},
list: {
  paddingBottom: 16,
},
receiptItem: {
  backgroundColor: '#f9f9f9',
  padding: 20,
  marginVertical: 8,
  borderRadius: 10,
  shadowColor: '#000',
  shadowOpacity: 0.1,
  shadowRadius: 5,
  shadowOffset: { width: 0, height: 2 },
  borderWidth: 1,
  borderColor: 'black', 
  width:300,
},
HistoryTitle: {
  fontSize: 30,
  fontWeight: 'bold',
  marginBottom: 16,
  textAlign: 'center',
  marginTop:15,
},
});





